spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 1234
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jooq:
    sql-dialect: postgres
logging:
  pattern:
    dateformat: yyyy-MMM-dd HH:mm:ss
springdoc:
  swagger-ui:
    csrf:
      enabled: true
